'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace MyPortfolioMVC.Models

    Public Partial Class MyPortfolio
        Inherits DbContext
        Public Sub New()
            MyBase.New("name=MyPortfolio")
        End Sub

        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub

        Public Overridable Property sysdiagrams As DbSet(Of sysdiagrams)
        Public Overridable Property TblAbouts As DbSet(Of TblAbouts)
        Public Overridable Property TblBanners As DbSet(Of TblBanners)
        Public Overridable Property TblCategories As DbSet(Of TblCategories)
        Public Overridable Property TblContacts As DbSet(Of TblContacts)
        Public Overridable Property TblEducation As DbSet(Of TblEducation)
        Public Overridable Property TblExperiensies As DbSet(Of TblExperiensies)
        Public Overridable Property TblExpertises As DbSet(Of TblExpertises)
        Public Overridable Property TblMessages As DbSet(Of TblMessages)
        Public Overridable Property TblProjects As DbSet(Of TblProjects)
        Public Overridable Property TblSocialMedias As DbSet(Of TblSocialMedias)
        Public Overridable Property TblTestimonials As DbSet(Of TblTestimonials)
    End Class
End Namespace
