'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Namespace MyPortfolioMVC.Models

    Public Partial Class sysdiagrams
        Public Property name As String
        Public Property principal_id As Integer
        Public Property diagram_id As Integer
        Public Property version As Integer?
        Public Property definition As Byte()
    End Class
End Namespace
