'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Namespace MyPortfolioMVC.Models

    Public Partial Class TblAbouts
        Public Property AboutId As Integer
        Public Property ImageUrl As String
        Public Property Title As String
        Public Property Description As String
        Public Property CvUrl As String
    End Class
End Namespace
