'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Namespace MyPortfolioMVC.Models

    Public Partial Class TblBanners
        Public Property BannerId As Integer
        Public Property BannerTitle As String
        Public Property BannerDesciription As String
        Public Property IsShown As Boolean?
    End Class
End Namespace
