//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolioMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBanners
    {
        public int BannerId { get; set; }
        public string BannerTitle { get; set; }
        public string BannerDesciription { get; set; }
        public Nullable<bool> IsShown { get; set; }
    }
}
