'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Namespace MyPortfolioMVC.Models

    Public Partial Class TblEducation
        Public Property EducationId As Integer
        Public Property SchoolName As String
        Public Property Department As String
        Public Property StartDate As Date?
        Public Property EndDate As Date?
        Public Property Description As String
        Public Property Degree As String
    End Class
End Namespace
