'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Namespace MyPortfolioMVC.Models

    Public Partial Class TblMessages
        Public Property MessageId As Integer
        Public Property Name As String
        Public Property Email As String
        Public Property Subject As String
        Public Property MessageContent As String
        Public Property IsRead As Boolean?
    End Class
End Namespace
