'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.ComponentModel.DataAnnotations

Namespace MyPortfolioMVC.Models

    Public Partial Class TblProjects
        Public Property ProjectId As Integer
        <Required(ErrorMessage:="Proje Adı Boş Geçilemez")>
        Public Property Name As String
        <Required(ErrorMessage:="Görsel Url Boş Geçilemez")>
        Public Property ImageUrl As String
        <Required(ErrorMessage:="Proje Açıklaması Boş Geçilemez")>
        <MaxLength(250, ErrorMessage:="Açıklama bölümü en fazla 250 karakter olmalıdır.")>
        Public Property Description As String
        <Required(ErrorMessage:="Kategori Boş Geçilemez")>
        Public Property CategoryId As Integer
        <Required(ErrorMessage:="Githup Linki Boş Geçilemez")>
        Public Property GithupUrl As String

        Public Overridable Property TblCategories As TblCategories
    End Class
End Namespace
