'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Namespace MyPortfolioMVC.Models

    Public Partial Class TblTestimonials
        Public Property TestimonialId As Integer
        Public Property NameSurname As String
        Public Property Title As String
        Public Property ImageUrl As String
        Public Property Comment As String
    End Class
End Namespace
